### PR TITLE
Upstream Updates + Ajax views fix

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Pulls down from upstream to get the latest updates
- Adds fix for issue when using blocks, panels, and ajax views where the pattern incorrectly thinks it is in admin preview. 

# Needed By (Date)
- Sometime between the 24th -> 28th

# Urgency
- Medium low

# Steps to Test

1. Review code commit https://github.com/SU-SWS/ui_patterns/commit/fd504e695b60c82b1a3dab5c655bbc176852b00e
2. Make comments

# Affected Projects or Products
- Just earth

# Associated Issues and/or People
- EARTH-955

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
@pookmish 
Poke

**Comment by pookmish** [comment]
you're poke no workie.

**Comment by sherakama** [comment]
https://media.giphy.com/media/U5BCh5lBoKpuE/giphy.gif

**Comment by pookmish** [comment]
poke

oh giphy must no workie

**Review by pookmish — APPROVED** [review]
Seems good

**Comment by sherakama** [comment]
Danke!

**Pull request merged**
